### ISSUE TITLE
몇가지 동작오류

### ISSUE THREAD

**Issue by happytk** [happytk/autoinsight-frontend#8]
1. preprocess화면에서 타겟, 피처를 선택했다가 해제했다가 하면, 실제 isTarget이 두 개 이상 설정되어서 automl수행시 오류 발생
2. leaderboard에서 lime표시안됨 -> 코드보니 dataType:'html' -> 'json'이어야 하고 결과의 limeHtml을 받아서 보여주어야 합니다.
3. leaderboard에서 stat이 잘 나오지 않네요. 확인부탁
4. deploy에서 lime표시안됨 -> leaderboard처럼 iframe으로 감싸서 넣어주세요. limeHtml필드에 마찬가지로 접근해야 하는데 그런 코드가 안보이네요.

**Comment by happytk** [comment]
5. Automl 시작시 오류 발생하면 서버 메시지를 보여주세요.

**Comment by happytk** [comment]
1번 현재 기준으로 테스트해보는데 잘 안되네요;

**Comment by kajmokr** [comment]
@happytk 어떤 케이스에서 오류가 발생하는지 자세히 알 수 있을까요? 저한테는 오류가 안나네요ㅜㅜ

**Comment by happytk** [comment]
@kajmokr 그냥 target을 차례대로 위에서부터 선택해보면 다음 target선택할때 이전 target도 true로 남아있어요.

**Comment by happytk** [comment]
@kajmokr frontend 새로 구성해서 이미지를 만들었는데 제가 실수했거나 캐싱때문에 착각했거나 싶어요. 잘 되고 있습니다. sorry!
